#!/bin/bash

set -e

# Don't run anything before this source as it sets PATH here
source /etc/profile

# load config
source /usr/sbin/resin-vars
source /etc/resin-supervisor/supervisor.conf

VERSION=@RESINOS_HASSIO_VERSION@

#
# MAIN
#
while read cmd
do
    IFS=" " read -r -a parse <<< $cmd

    if [ ${parse[0]} == "info" ]; then
        HOSTNAME=$(hostname)
        OS=$(uname -o)
        LAST=$(curl -s $ENDPOINT | jq -e -r '.resinos')
        FEATURES="[\"shutdown\", \"reboot\", \"update\"]"

        echo "{ \"type\": \"resinos\", \"version\": \"$VERSION\", \"last_version\": \"$LAST\", \"hostname\": \"$HOSTNAME\", \"features\": $FEATURES, \"os\": \"$OS\" }"
        continue
    fi
    if [ ${parse[0]} == "reboot" ]; then
        systemctl reboot && echo "OK" || echo "ERROR"
        continue
    fi
    if [ ${parse[0]} == "shutdown" ]; then
        systemctl poweroff && echo "OK" || echo "ERROR"
        continue
    fi
    if [ ${parse[0]} == "update" ]; then
        if [ ! -z ${parse[1]} ]; then
            nohup resinhup --hostos-version ${parse[1]} > /dev/null 2>&1 &
        else
            nohup resinhup > /dev/null 2>&1 &
        fi
        echo "OK"
        continue
    fi

    echo "WRONG"
done
